name: Deploy from latest dev branch

on:
  push:
    branches:
      - ultra-dex

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v1

      - name: Setup Docker
        uses: docker-practice/actions-setup-docker@0.0.1

      - name: Log in to Docker registry
        run: |
          echo ${{ secrets.DOCKER_HUB_PASSWORD }} | docker login \
            --username ${{ secrets.DOCKER_HUB_USER }} \
            --password-stdin

      - name: Build Docker images
        run: |
          make build-docker-images
        env:
          DOCKER_HUB_USER: ${{ secrets.DOCKER_HUB_USER }}
          PROXY_HOST: nuxt.ultradex

      - name: Push Docker images
        run: |
          make push-docker-images
        env:
          DOCKER_HUB_USER: ${{ secrets.DOCKER_HUB_USER }}
          DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build Kubernetes namespace
        run: |
          make build-kubernetes-namespace
        env:
          DOCKER_HUB_USER: ${{ secrets.DOCKER_HUB_USER }}
          NAMESPACE: ${{ secrets.NAMESPACE }}
          INGRESS_HOST: ${{ secrets.INGRESS_HOST }}
          NETWORK: eos
          PROTOCOL: https
          DB_STRING_CONNECTION: mongodb://mongo.ultradex:27017/alcor_prod

      - name: Push Kubernetes namespace
        uses: steebchen/kubectl@v1.1.0
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
          NAMESPACE: ${{ secrets.NAMESPACE }}
        with:
          args: version && make push-kubernetes-namespace
